# Generated by Django 4.0.2 on 2022-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
