# Generated by Django 4.0.2 on 2022-05-06 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_like_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
    ]
