# Generated by Django 4.0.2 on 2022-05-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
